jobs:
  generate-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 拉取倉庫代碼

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # 指定 Python 版本

      # 新增：安裝 pandas-datareader（關鍵步驟）
      - name: Install pandas-datareader
        run: |
          pip install pandas-datareader==0.10.0  # 安裝穩定版

      # 安裝其他依賴（如 pandas、plotly 等）
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 若有 requirements.txt

      - name: Run main.py
        run: |
          python main.py  # 執行主程式
