jobs:
  generate-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 新增：安裝 pandas-datareader
      - name: Install pandas-datareader
        run: |
          pip install pandas-datareader

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 若有其他依賴

      - name: Run main.py
        run: |
          python main.py
