jobs:
  generate-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 關鍵修改：指定 main.py 所在的子目錄
      - name: Run main.py
        working-directory: ./scripts  # 替換為實際子目錄名（如 src/）
        run: |
          python main.py  # 此時路徑為 ./scripts/main.py
