name: Generate Tencent OHLC Chart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 18 * * 1-5'  # 每個工作日 UTC 時間 18:00 運行 (香港時間凌晨2點)
  workflow_dispatch:  # 允許手動觸發

jobs:
  generate-chart:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas plotly yfinance

      - name: Create data directory
        run: mkdir -p stock_data

      - name: Run Python script to generate chart
        run: python main.py

      - name: List generated files
        run: |
          echo "Generated files in stock_data/:"
          ls -la stock_data/
          echo -e "\nFile sizes:"
          du -h stock_data/* || true

      - name: Verify HTML file exists
        id: verify-html
        run: |
          if [ -f "stock_data/0700_HK_candlestick.html" ]; then
            echo "HTML_FILE_EXISTS=true" >> $GITHUB_OUTPUT
            echo "✅ HTML file generated successfully"
          else
            echo "HTML_FILE_EXISTS=false" >> $GITHUB_OUTPUT
            echo "❌ HTML file not found!"
          fi

      - name: Verify CSV file exists
        id: verify-csv
        run: |
          if [ -f "stock_data/0700_HK.csv" ]; then
            echo "CSV_FILE_EXISTS=true" >> $GITHUB_OUTPUT
            echo "✅ CSV file generated successfully"
          else
            echo "CSV_FILE_EXISTS=false" >> $GITHUB_OUTPUT
            echo "❌ CSV file not found!"
          fi

      - name: Upload HTML chart artifact
        if: steps.verify-html.outputs.HTML_FILE_EXISTS == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: tencent-ohlc-chart
          path: stock_data/0700_HK_candlestick.html
          retention-days: 7

      - name: Upload CSV data artifact
        if: steps.verify-csv.outputs.CSV_FILE_EXISTS == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: tencent-stock-data
          path: stock_data/0700_HK.csv
          retention-days: 7

      - name: Upload all artifacts as zip
        if: steps.verify-html.outputs.HTML_FILE_EXISTS == 'true' || steps.verify-csv.outputs.CSV_FILE_EXISTS == 'true'
        run: |
          cd stock_data
          zip -r ../generated_files.zip .
          cd ..
          echo "ZIP_FILE=generated_files.zip" >> $GITHUB_ENV

      - name: Upload zip artifact
        if: env.ZIP_FILE != ''
        uses: actions/upload-artifact@v4
        with:
          name: all-generated-files
          path: ${{ env.ZIP_FILE }}
          retention-days: 3

      - name: Success notification
        if: success()
        run: |
          echo "✅ Chart generation completed successfully!"
          echo "Artifacts available for download from Actions page"

      - name: Failure notification
        if: failure()
        run: |
          echo "❌ Chart generation failed!"
          echo "Check logs for details"
