name: Auto Update Stock Chart

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 點（北京時間 8 點）
  workflow_dispatch:     # 手動觸發

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      writes: write
    steps:
      - name: 檢出倉庫
        uses: actions/checkout@v4

      - name: 設定 Python 環境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安裝依賴
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple  # 清華鏡像源

      - name: 運行程式碼
        run: python stock_analysis.py

      - name: 提交更新（僅在主分支且成功時）
        if: github.ref == 'refs/heads/main' && success()
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto-update: $(date +%Y-%m-%d)"
          git push
